In [1]:
pip install -i https://mirrors.tuna.tsinghua.edu.cn/pypi/web/simple torch

Looking in indexes: https://mirrors.tuna.tsinghua.edu.cn/pypi/web/simple
  Using cached https://mirrors.tuna.tsinghua.edu.cn/pypi/web/packages/76/49/4a0a8b19ce8f9bf32fcab4e863c7e2366f519f9826c84ca250567b11a014/torch-2.5.1-cp39-cp39-win_amd64.whl (203.0 MB)



In [2]:
import torch

In [3]:
vec = torch.tensor([1.0,2.0,3.0]) #一维张量
print(vec)

tensor([1., 2., 3.])


In [7]:
mat = torch.tensor([[1,2],[3,4]])  #二维张量
print(mat)

tensor([[1, 2],
        [3, 4]])


In [8]:
print([1,2,3]+[4,5,6])

[1, 2, 3, 4, 5, 6]


In [10]:
tensor_1 = torch.tensor([[1,2,3,4]])
tensor_2 = torch.tensor([[5,6,7,8]])
print(torch.cat([tensor_1,tensor_2],dim=0))  #拼接
print(torch.cat([tensor_1,tensor_2],dim=1))

tensor([[1, 2, 3, 4],
        [5, 6, 7, 8]])
tensor([[1, 2, 3, 4, 5, 6, 7, 8]])


In [22]:
t = torch.ones(4,4)
print(t)
#类型转换
n = t.numpy()
print(n)

tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])
[[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]


In [1]:
pip install -i https://mirrors.tuna.tsinghua.edu.cn/pypi/web/simple torchvision

Looking in indexes: https://mirrors.tuna.tsinghua.edu.cn/pypi/web/simpleNote: you may need to restart the kernel to use updated packages.



In [3]:
from PIL import Image
from torchvision import transforms

image_path = r'无标题.png'
image = Image.open(image_path)

transform = transforms.ToTensor()
tensor_image = transform(image)

In [5]:
print(tensor_image)
print(type(tensor_image))

tensor([[[1.0000, 1.0000, 1.0000,  ..., 0.0000, 0.0000, 0.0000],
         [1.0000, 1.0000, 1.0000,  ..., 0.9686, 0.7176, 0.4392],
         [1.0000, 1.0000, 1.0000,  ..., 1.0000, 1.0000, 1.0000],
         ...,
         [1.0000, 1.0000, 1.0000,  ..., 1.0000, 1.0000, 1.0000],
         [1.0000, 1.0000, 1.0000,  ..., 1.0000, 1.0000, 1.0000],
         [1.0000, 1.0000, 1.0000,  ..., 1.0000, 1.0000, 1.0000]],

        [[1.0000, 1.0000, 1.0000,  ..., 0.0000, 0.0000, 0.0000],
         [1.0000, 1.0000, 1.0000,  ..., 0.9686, 0.7176, 0.4392],
         [1.0000, 1.0000, 1.0000,  ..., 1.0000, 1.0000, 1.0000],
         ...,
         [1.0000, 1.0000, 1.0000,  ..., 1.0000, 1.0000, 1.0000],
         [1.0000, 1.0000, 1.0000,  ..., 1.0000, 1.0000, 1.0000],
         [1.0000, 1.0000, 1.0000,  ..., 1.0000, 1.0000, 1.0000]],

        [[1.0000, 1.0000, 1.0000,  ..., 0.0000, 0.0000, 0.0000],
         [1.0000, 1.0000, 1.0000,  ..., 0.9686, 0.7176, 0.4392],
         [1.0000, 1.0000, 1.0000,  ..., 1.0000, 1.0000, 1.